on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: |
        npm install
      env:
        NODE_ENV: production
        NODE_VERSION: ${{ matrix.node-version }}

    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
        NODE_VERSION: ${{ matrix.node-version }}

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/tylerhjones.github.io.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}